### PR TITLE
added -b13 for ORIC tapes

### PR DESCRIPTION
**Pull request by rampa069**
added -b13 to process standard ORIC tapes (may be others)

### CODE REVIEW

**Comment by nataliapc** [comment]
Have you tried -b15 with that tapes?
Block#13 could be a very poor way to list a serie of pulses unless they were only a few ones.

**Comment by rampa069** [comment]
It works flawlessly with long tapes.  -b15 works nice with them, but a lot of players (including old tzxduino/maxduinos with old firmware) cant handle b15 blocks. so it is more for backwards compatibility. without this, sometimes maketsx detect a pilot tone and breaks the wav.. :-(

**Comment by nataliapc** [comment]
Ok I will add this. Thanks for the contribution!

Anyway could be great learn about the KCS variant of ORIC tapes and add a oric2tsx.php at:
https://github.com/nataliapc/MSX_devs/tree/master/TSXphpclass

Please contact me (@ishwin74 at twitter) if you are interested.

**Review by nataliapc — APPROVED** [review]
Added -b13 from ORIC scene. Thanks to rampa069.

**Pull request merged**
